apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: scraper_ops
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: scraper_ops_development
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: application
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
