apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:latest
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: guest
        - name: RABBITMQ_DEFAULT_PASS
          value: guest
        - name: RABBITMQ_DEFAULT_VHOST
          value: /
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: application
spec:
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq-port-5672
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: rabbitmq-port-15672
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: ClusterIP
